export const PRIEST_SPHERE_OPTIONS = [
  "All",
  "Animal",
  "Astral",
  "Charm",
  "Chaos",
  "Combat",
  "Cosmos",
  "Creation",
  "Divination",
  "Elemental",
  "Elemental Air",
  "Elemental Earth",
  "Elemental Fire",
  "Elemental Silt",
  "Elemental Water",
  "Guardian",
  "Healing",
  "Law",
  "Necromantic",
  "Numbers",
  "Plant",
  "Protection",
  "Summoning",
  "Sun",
  "Thought",
  "Time",
  "Travelers",
  "War",
  "Wards",
  "Weather",
] as const;
